### ISSUE TITLE
Audio player protrudes in smartphone display

### ISSUE THREAD

**Issue by miyaoka** [tofu-ninjin/tofu-ninjin#23]
<img width="401" alt="2018-06-05 23 54 36" src="https://user-images.githubusercontent.com/1443118/40984158-2192b5ae-691c-11e8-9fc3-fd1af6ef5dbd.png">

#22 の対応なのですがiPhoneXのサイズでも収まらないみたいです

**Comment by y0za** [comment]
報告ありがとうございます:+1:
一応横幅が収まるように修正したので問題なくなったかと思います

<img width="422" alt="tofu-ninjin-player02" src="https://user-images.githubusercontent.com/16757772/40989776-d8c76bc2-6929-11e8-986f-44f38e93ddb9.png">

**Comment by y0za** [comment]
報告ありがとうございます:+1:
一応横幅が収まるように修正したので問題なくなったかと思います

<img width="422" alt="tofu-ninjin-player02" src="https://user-images.githubusercontent.com/16757772/40989776-d8c76bc2-6929-11e8-986f-44f38e93ddb9.png">

**Comment by miyaoka** [comment]
ありがとうございます！
ちゃんと収まることを確認しました！

あとちょっと別問題になるんですが、
スマホ実機で操作した場合、スライダーの操作がきかないようです。
input type=rangeでスライダーUI作れるんですが、たしかtouch eventが対応してなくて
なんかsoussuneでもそのへん結局独自対応した覚えがあります。
あと音量コントロールもhtml audioだと仕様的にスマホでは制御できないですね（ミュートは可）

**Comment by y0za** [comment]
確認してみたところAndroidのChromeだと問題ないですがiOSのSafariだと色々動かないですねー😓
とりあえずスライダーの操作などできる範囲で対応してみようと思います。

**Comment by miyaoka** [comment]
あーそうですね。safariが対応してないって話でした。
とりあえずこのIssueは解決済みなのでcloseします
