### ISSUE TITLE
Add Open Graph meta tags

### ISSUE THREAD

**Issue by miyaoka** [tofu-ninjin/tofu-ninjin#32]
twitterやfbでシェアするときに表示が良くなるように各ページにOGPタグも設定したい

```
<meta property="og:title"       content="OGPのタイトル">
<meta property="og:description" content="OGPのディスクリプション">
<meta property="og:image"       content="http://foo.com/bar.jpg">
```

Helmetのmetaに追加していく感じ

## validator

OGP設定したらこちらにURL入れて確認できます

twitter
https://cards-dev.twitter.com/validator

facebook
https://developers.facebook.com/tools/debug/

## Example

https://github.com/soussune/soussune.com/search?q=og%3Atitle&unscoped_q=og%3Atitle

soussuneだと共通設定、エピソード一覧/詳細、出演者一覧/詳細、とそれぞれに設定してます

**Comment by y0za** [comment]
反応が遅れて申し訳ないです 😅
指摘していただいた情報を基にいくつかタグを追加してみました。

**Comment by y0za** [comment]
`og:url` も対応したので最低限必要そうなものは追加できたかと思います。

**Comment by miyaoka** [comment]
対応ありがとうございます！最高です！！
index, episode, speakerそれぞれで表示されることを確認しました。
